### ISSUE TITLE
[BUG] When a service is binded to the cloud-service-broker-azure-X.X.XX app, we get "Error parsing VCAP_SERVICES: Error finding MySQL tag"

### ISSUE THREAD

**Issue by drebake** [pivotal/cloud-service-broker#93] opened 2020-09-17 13:04 UTC
## Description
We did a tile installation. So we create a p.mysql database for the cloud-service-broker database. We then create a access-key to that service and used that information in the  database settings of the "Service Broker Config" tab in the tile.

If we then bind a service to the cloud-service-broker-azure-X.X.XX app (Splunk log drain in our case), we get "Error parsing VCAP_SERVICES: Error finding MySQL tag" and the app doesn't start.

It appears like it's trying to find the database information from the VCAP_SERVICES.

If I then bind the cloud-service-broker-azure-X.X.XX app to my mysql database service. It then finds the VCAP_SERVICE information and the app starts normally and enables us to use the splunk log drain.

## Expected Behavior
When binding another service, the cloud-service-broker should still use the information provided in the in the tile configuration.

## Actual Behavior
When a service binding is present at the app start time, it looks in the VCAP_SERVICE for the mysql database.

## Possible Fix
Be able to bind an external service and still use the configured database information and not look in VCAP_SERVICES if those settings are provided by the tile configuration.

## Steps to Reproduce
1. Create a Mysql database
2. Install the tile and provided the access-key information of the Mysql database.
3. Bind a external service (ex: splunk log drain)
4. Restart the cloud-service-broker-azure-X.X.XX app

## Context
We had to bind to the database and we must also keep our service-key in order to be able to provide that informaiton to the tile configuration. We then have to make available two set's of credentials to the cloud-service-broker app in order to be able to use our log drain.

## Your Environment
Version used: Cloud service broker for Microsoft Azure 0.0.35
Platform (Azure/AWS/GCP): Azure
Applicable Services: Bosh 2.10.1 TAS: 2.10.3

## Full error log
2020-09-16T15:18:13.720-04:00 [APP/PROC/WEB/0] [OUT] {"timestamp":"1600283893.719773531","source":"cloud-service-broker","message":"cloud-service-broker.Invalid VCAP_SERVICES environment variable","log_level":2,"data":{"error":"Error parsing VCAP_SERVICES: Error finding MySQL tag: The variable VCAP_SERVICES must have one VCAP service with a tag of 'mysql'. There are currently 0 VCAP services with the tag 'mysql'."}}

2020-09-16T15:18:13.720-04:00 [APP/PROC/WEB/0] [ERR] {"timestamp":"1600283893.719773531","source":"cloud-service-broker","message":"cloud-service-broker.Invalid VCAP_SERVICES environment variable","log_level":2,"data":{"error":"Error parsing VCAP_SERVICES: Error finding MySQL tag: The variable VCAP_SERVICES must have one VCAP service with a tag of 'mysql'. There are currently 0 VCAP services with the tag 'mysql'."}}

2020-09-16T15:18:13.774-04:00 [APP/PROC/WEB/0] [OUT] Exit status 1

**Comment by erniebilling** [comment] 2020-09-17 16:24
@drebake Currently, the broker expects mysql bindings in VCAP_SERVICES if VCAP_SERVICES is present. There is no fallback to the environment variables when VCAP_SERVICES is present but there is no mysql binding found.

Is binding splunk log drain the only way to get splunk to collect logs from the broker?

**Comment by drebake** [comment] 2020-09-17 16:36
I haven't investigated but there might be other ways, but that's how we currently have it configured for all our other apps. I think the issue is that the broker sees a VCAP_SERVICES since the log-drain is binded.... 

Shouldn't the broker look at the type of service binded before simply falling back to the VCAP_SERVICES for the database information?

**Comment by erniebilling** [comment] 2020-09-17 17:24
The issue is that Google designed the broker to be installed as a tile (no VCAP_SERVICES) and didn't expect the split config. Since the broker itself is not doing anything with the splunk binding, its only expecting to be bound to a database.

There is no reason to bind these services to the broker, its not going to do anything with any of the credentials in VCAP_SERVICES. There must be some other side effect of the binding that splunk is using to collect logs, because the broker isn't doing anything to help splunk collect logs.

We'll have a look at fixing this issue.

**Comment by omerbensaadon** [comment] 2020-09-23 13:04
@drebake check TanzuNet for `0.0.39-azure-beta`! Closing this issue, but feel free to re-open if you give it a try and it doesn't work as expected.

**Closed by omerbensaadon** 2020-09-23 13:04 UTC
Labels: azure, bug, opsman-tile

**Comment by drebake** [comment] 2020-09-23 14:26
I can confirm, we can now bind our Splunk drain and restart the broker app with no issues.
Thanks!
