### ISSUE TITLE
[BUG] sql failover group db update does not propagate changes to secondary db

### ISSUE THREAD

**Issue by omerbensaadon** [pivotal/cloud-service-broker#63] opened 2020-08-10 20:21 UTC
## Description

Running `cf update-service fog-S0-update -p standard-S3 -c '{"server_pair":"pair_xxx"}' does not update plan size on the secondary db

## Expected Behavior

running cf update-service fog-S0-update -p standard-S3 -c '{"server_pair":"pair_xxx"}' should reflect changes in primary and secondary db

## Actual Behavior

running cf update-service fog-S0-update -p standard-S3 -c '{"server_pair":"pair_xxx"}' only reflects changes on primary db

## Possible Fix

Fix for terraform provider or the Azure APIs that the provider uses

## Steps to Reproduce

1. Create a FOG db instance
2. Try and update that instance to a different plan size
3. See that the primary db successfully updates
4. See that the secondary db does now

## Context

This is an extension of the FR submitted by @drebake #47. The Feature Request was delivered, but the functionality is incomplete due to circumstances beyond the team's control (see #47 for context

## Your Environment

* Version used: Bosh 2.9.6, TAS 2.9.7, cf version 6.51.0+2acd15650.2020-04-07, sb-0.1.0-rc.35-azure-0.0.1-rc.112 
* Operating System and version (desktop): N/A
* Link to your project (if public): N/A 
* Platform (Azure/AWS/GCP): Azure
* Applicable Services: Azure Failover Groups

**Comment by omerbensaadon** [comment] 2020-08-10 20:36
We have submitted an issue in the terraform-provider-azurerm repo (https://github.com/terraform-providers/terraform-provider-azurerm/issues/8040) in an attempt to get this addressed

**Comment by erniebilling** [comment] 2020-09-23 17:16
There is a workaround fix for this released now. See https://github.com/pivotal/cloud-service-broker/blob/master/docs/mssql-db-fog-config.md#notes-on-the-secondary-db-created-by-fog

A more comprehensive fix may be implemented in the future.

**Closed by erniebilling** 2020-09-23 17:16 UTC
Labels: azure, bug, external-dependency

**Comment by omerbensaadon** [comment] 2020-09-23 18:06
@drebake see above related to #47, let us know if this fixes the issue for you!

**Comment by drebake** [comment] 2020-09-23 20:16
Should it work with version Azure tile 0.0.39? I just tried with a csb-azure-mssql-db-failover-group service and it didn't update the secondary database.

Steps:
1-  cf create-service csb-azure-mssql-db-failover-group standard-S0 fog1 -c '{"server_pair":"pair1"}'
2- cf service fog1
3- cf create-service csb-masb-mssql-db-subsume current secondary-db -c '{"azure_db_id":"/subscriptions/XXXXXXXXXXXX-4140-8c5c-XXXXXXXXXX/resourceGroups/sqldb-cfzcea-rg/providers/Microsoft.Sql/servers/sqldb-cfzcea-csb-server01/databases/csb-fog-db-XXXXXXXX-XXXXX-XXXX-XXXX-XXXXXXXXXXXa2"}'
4- cf update-service fog1 -p standard-S3 -c '{"server_pair":"pair1"}'

Primary update to standard-S3 but not the secondary.

**Comment by erniebilling** [comment] 2020-09-23 20:45
Yes, that is the way its going to work for now. cf update secondary-db is necessary to update the sku for the secondary db.

**Comment by drebake** [comment] 2020-09-23 21:16
I did an update-service with the server_pair as a parameter,

cf update-service fog2-secondary -c '{"server_pair":"pair1"}'

I then got a update-failed.

 2020-09-23T16:58:00.56-0400 [APP/PROC/WEB/0] OUT {"timestamp":"1600894680.561564445","source":"terraform@/home/vcap/tmp/gsb248689954","message":"terraform@/home/vcap/tmp/gsb248689954.results","log_level":1,"data":{"error":{"Stderr":null},"errors":"\nError: failure in issuing create/update request for SQL Database \"csb-fog-db-728a0821-4cbc-4712-b27a-0583286fe64b\" Blob Auditing Policies(SQL Server \"sqldb-cfzcea-csb-server01\"/ Resource Group \"sqldb-cfzcea-rg\"): sql.ExtendedDatabaseBlobAuditingPoliciesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\"BlobAuditingIsNotSupportedOnGeoDr\" Message=\"Blob auditing can be configured on primary databases only.\"\n\n  on main.tf line 2, in resource \"azurerm_sql_database\" \"azure_sql_db\":\n   2: resource \"azurerm_sql_database\" \"azure_sql_db\" {\n\n\n","output":"azurerm_sql_database.azure_sql_db: Refreshing state... [id=/subscriptionsXXXXXXXXXXXXXXXXXXXXXXXX/resourceGroups/sqldb-cfzcea-rg/providers/Microsoft.Sql/servers/sqldb-cfzcea-csb-server01/databases/csb-fog-db-728a0821-4cbc-4712-b27a-0583286fe64b]\ndata.azurerm_sql_server.azure_sql_db_server: Refreshing state...\nazurerm_sql_database.azure_sql_db: Modifying... [id=/subscriptions/4e6ece19-da08-4140-8c5c-1bf426457448/resourceGroups/sqldb-cfzcea-rg/providers/Microsoft.Sql/servers/sqldb-cfzcea-csb-server01/databases/csb-fog-db-728a0821-4cbc-4712-b27a-0583286fe64b]\n"}}

**Comment by erniebilling** [comment] 2020-09-23 22:16
It doesn't work that way.

See the results of `cf service fog2-secondary`  That should output the edition and service_objective for the current state of the database. You can then change the service_objective to change the sku of the db:

`cf update-service fog2-secondary -c '{"service_objective":"<new objective>"}'`

The secondary is a completely separate resource in CF's perspective, no connection to the FOG, so you manage it as its own entity.

**Comment by drebake** [comment] 2020-09-24 12:16
I can confirm that with the "cf update-service fog2-secondary -c '{"service_objective":"<new objective>"}'" command, I can change the SKU of the secondary database.

Is there a reason why a secondary service was created to perform the update-service and delete service of the secondary database and not just included in the "csb-azure-mssql-db-failover-group"? I don't see a case where you would want to have a different secondary database or not have the secondary database deleted from a "csb-azure-mssql-db-failover-group" command.

**Comment by erniebilling** [comment] 2020-09-24 16:23
The root of the problem is that both terraform and the Azure API's it relies on don't directly manage the secondary DB. That DB is created as a side-effect of creating the FOG. With the subsume support (based on terraform import) we have now have the tools to gain control of that DB, but don't have all the internal plumbing in the broker to automate that (run terraform apply to create the FOG, then run a terraform import to gain control of the out of bounds creation of the secondary DB.) This manual subsume step is a work around while we prioritize the core broker effort to make it work end to end.
